name: Test Workflow
on:
  pull_request:
    types: [closed]
  push:

jobs:
  push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - run: jq <<< '${{ toJSON(github) }}'

  pull_requst_closed:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: jq <<< '${{ toJSON(github) }}'

  default:
    if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: jq <<< '${{ toJSON(github) }}'
